---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[php]
      - recipe[composer]
    attributes:
      php:
        packages: [php56, php56-devel, php56-cli, php56-pear]
        mysql:
          package: php56-mysqlnd
        fpm_package: php56-fpm
